version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11

  build:
    commands:
      - IMAGE_REPO_NAME=gabrielgrazziani-ot5-containers
      - AWS_ACCOUNT_ID="$account_id"
      - AWS_DEFAULT_REGION=sa-east-1
      - IMAGE_TAG=latest
      - URL_ECR = $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $URL_ECR .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push $URL_ECR
      - echo '[{"name":"codebuild-docker","imageUri":"$URL_ECR"}]' > imagedefinitions.json
      - sh build.sh

artifacts:
  files:
    - imagedefinitions.json
