#!/bin/bash
aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin 208471844409.dkr.ecr.us-east-1.amazonaws.com/ot5-gabrielgrazziani-containers

isExisApp=`podman ps | grep codebuild-docker`
if [[ -n $isExisApp ]]; then
  podman rm -f codebuild-docker
fi
podman run -p 8080:80 -dt --name codebuild-docker 208471844409.dkr.ecr.us-east-1.amazonaws.com/ot5-gabrielgrazziani-containers:latest