#!/bin/bash
aws ecr get-login-password --region us-east-2 | podman login --username AWS --password-stdin 208471844409.dkr.ecr.us-east-2.amazonaws.com/gabrielgrazziani-ot5-containers

isExisApp=`podman ps | grep codebuild-docker`
if [[ -n $isExisApp]]; then
  podman rm -f codebuild-docker && podman run -p 8080:80 -dt --name codebuild-docker 208471844409.dkr.ecr.us-east-2.amazonaws.com/gabrielgrazziani-ot5-containers:latest
fi